name: test

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Compile
      run: cmake -B build && cmake --build build
    - name: Test
      run: cd build/test && sudo chmod +x ../script.sh && sudo chmod +x ./test.sh && sudo ./test.sh
    
