name: test

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Compile
      run: sudo chmod +x ./compile.sh && ./compile.sh
    - name: Test
      run: cd Test && sudo chmod +x ./test.sh && sudo ./test.sh
    
